[정렬, 맵, 셋] 8월 20일
Altu-Bitu-7/Altu-Bitu-KimYewon pull request #1
Opened 2024-08-20 09:58 UTC by wonnn25

###인적사항
학번: 2171060
이름: 김예원

##과제제출
기존제출: 0820

2024-08-25 14:22 UTC, chae-jpg approved these changes
**[정렬, 맵, 셋 구현 코드리뷰 완료]**
14425(P3) 
예원님 안녕하세요! 코드 리뷰 완료되었습니다👍 
몇 가지 사소한 코멘트 남겼습니다! 
궁금하신 점이 있다면 언제나 리뷰어를 호출해주세요😊

2024-08-25 14:22 UTC, chae-jpg commented on 01_정렬_맵_셋/14425.cpp
> +	//�Է� & ����
주석 달아주신 점 너무 좋아요! 다만 주석이 깨져서 확인할 수 없는 점이 너무 아쉽습니다 😢

2024-08-25 14:22 UTC, chae-jpg commented on 01_정렬_맵_셋/14425.cpp
> +	map<string, int> s;
탐색에 용이한 맵 자료구조를 사용해서 문제를 효율적으로 해결해주셨네요!

2024-08-25 14:22 UTC, chae-jpg commented on 01_정렬_맵_셋/14425.cpp
> +	}
P3
알튜비튜에서는 입출력을 제외한 코드는 다른 함수로 분리하는 것을 권장하고 있습니다. 
입출력은 메인에 두고, 탐색하는 부분은 findString과 같은 이름의 함수로 분리하면 더 좋을 것 같아요!👍

2024-08-25 17:20 UTC, flowing1ife requested changes
[정렬, 맵, 셋 구현 코드리뷰 완료]
1431(P1) 

코드 리뷰 완료하였습니다 !
몇 가지 사소한 코멘트 남겼으니 확인해주세요 😊

2024-08-25 17:20 UTC, flowing1ife commented on 01_정렬_맵_셋/1431.cpp
> +	//�Է�
P3
주석이 깨집니다 ㅜ

2024-08-25 17:20 UTC, flowing1ife commented on 01_정렬_맵_셋/1431.cpp
> +	string serial_num_arr[50]; //�ø���ѹ�
P1
string이 아닌 vector를 사용해서 n개만큼 초기화해준다면 메모리 측면에서도 효율적이고 훨씬 더 코드가 간결해져요 !

2024-08-25 17:20 UTC, flowing1ife commented on 01_정렬_맵_셋/1431.cpp
> +		if (num >= 0 && num <= 9) { //�����̸�
P2
isdigit 함수를 사용하면 숫자의 여부를 바로 확인할 수 있어요 !

2024-09-03 09:53 UTC, wonnn25 commented on 01_정렬_맵_셋/14425.cpp
> +	}
수정하였습니다!

2024-09-03 09:53 UTC, wonnn25 commented on 01_정렬_맵_셋/1431.cpp
> +	//�Է�
수정하였습니다!

2024-09-03 09:54 UTC, wonnn25 commented on 01_정렬_맵_셋/1431.cpp
> +	string serial_num_arr[50]; //�ø���ѹ�
반영하여 수정했습니다!

2024-09-03 09:54 UTC, wonnn25 commented on 01_정렬_맵_셋/1431.cpp
> +		if (num >= 0 && num <= 9) { //�����̸�
수정하였습니다!

2024-09-17 08:44 UTC, merged